### ISSUE TITLE
Problem opening input file.

### ISSUE THREAD

**Issue by eddip** [Illumina/akt#14]
Hi there,

I'm having an issue with akt using the pca option.

It gives me the following error when it looks to open my input bcf file.

command string : $ /g/data/a32/Software/akt/akt pca /short/a32/exi569/GB_CHD_NDD/CHD_NDD_all_samples_SNPS_PCA_ID.bcf -R /g/data/a32/Software/akt/data/wes.hg19.vcf.gz -O b -o /short/a32/exi569/GB_CHD_NDD/pca.bcf > /short/a32/exi569/GB_CHD_NDD/pca.txt

Console reply : 
Input: /short/a32/exi569/GB_CHD_NDD/CHD_NDD_all_samples_SNPS_PCA_ID.bcf
MAF lower bound: 0
Thin: 1
Number principle components: 20
Reading data...
Problem opening /short/a32/exi569/GB_CHD_NDD/CHD_NDD_all_samples_SNPS_PCA_ID.bcf
Input: /short/a32/exi569/GB_CHD_NDD/CHD_NDD_all_samples_SNPS_PCA_ID.bcf

I have no problem opening and viewing the "CHD_NDD_all_samples_SNPS_PCA_ID.bcf" input file using bcftools view.

[exi569@raijin3 GB_CHD_NDD]$ bcftools view CHD_NDD_all_samples_SNPS_PCA_ID.bcf | more                                                              ##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##source=VarScan2
##INFO=<ID=ADP,Number=1,Type=Integer,Description="Average per-sample depth of bases with Phred score >= 20">
##INFO=<ID=WT,Number=1,Type=Integer,Description="Number of samples called reference (wild-type)">
##INFO=<ID=HET,Number=1,Type=Integer,Description="Number of samples called heterozygous-variant">
##INFO=<ID=HOM,Number=1,Type=Integer,Description="Number of samples called homozygous-variant">
##INFO=<ID=NC,Number=1,Type=Integer,Description="Number of samples not called">
##FILTER=<ID=str10,Description="Less than 10% or more than 90% of variant supporting reads on one strand">
##FILTER=<ID=indelError,Description="Likely artifact due to indel reads at this position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=SDP,Number=1,Type=Integer,Description="Raw Read Depth as reported by SAMtools">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Quality Read Depth of bases with Phred score >= 20">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=PVAL,Number=1,Type=String,Description="P-value from Fisher's Exact Test">
##FORMAT=<ID=RBQ,Number=1,Type=Integer,Description="Average quality of reference-supporting bases (qual1)">
##FORMAT=<ID=ABQ,Number=1,Type=Integer,Description="Average quality of variant-supporting bases (qual2)">
##FORMAT=<ID=RDF,Number=1,Type=Integer,Description="Depth of reference-supporting bases on forward strand (reads1plus)">
##FORMAT=<ID=RDR,Number=1,Type=Integer,Description="Depth of reference-supporting bases on reverse strand (reads1minus)">
##FORMAT=<ID=ADF,Number=1,Type=Integer,Description="Depth of variant-supporting bases on forward strand (reads2plus)">
##FORMAT=<ID=ADR,Number=1,Type=Integer,Description="Depth of variant-supporting bases on reverse strand (reads2minus)">
##contig=<ID=chr1>
##contig=<ID=chr2>
##contig=<ID=chr3>
##contig=<ID=chr4>
##contig=<ID=chr5>
##contig=<ID=chr6>
##contig=<ID=chr7>
##contig=<ID=chr8>
##contig=<ID=chr9>
##contig=<ID=chr10>
##contig=<ID=chr11>
##contig=<ID=chr12>
##contig=<ID=chr13>
##contig=<ID=chr14>
##contig=<ID=chr15>
##contig=<ID=chr16>
##contig=<ID=chr17>
##contig=<ID=chr18>
##contig=<ID=chr19>
##contig=<ID=chr20>
##contig=<ID=chr21>
##contig=<ID=chr22>
##contig=<ID=chrX>
##bcftools_mergeVersion=1.3.1+htslib-1.3.1
##bcftools_mergeCommand=merge -O z -o CHD_NDD_samples_SNPS.vcf.gz 02766-recalBAMS_SNPS.vcf.gz 00618-recalBAMS_SNPS.vcf.gz 00714-recalBAMS_SNPS.vcf.
gz 01152-recalBAMS_SNPS.vcf.gz 01299-recalBAMS_SNPS.vcf.gz 00773-recalBAMS_SNPS.vcf.gz 00928-recalBAMS_SNPS.vcf.gz 01023-recalBAMS_SNPS.vcf.gz 0185
0-recalBAMS_SNPS.vcf.gz 00626-recalBAMS_SNPS.vcf.gz 00734-recalBAMS_SNPS.vcf.gz 02503-recalBAMS_SNPS.vcf.gz 00720-recalBAMS_SNPS.vcf.gz 01330-recal
BAMS_SNPS.vcf.gz 00748-recalBAMS_SNPS.vcf.gz
##bcftools_mergeCommand=merge -O z -o CHD_NDD_all_samples_SNPS.vcf.gz CHD_NDD_samples_SNPS.vcf.gz CHD_samples_SNPS.vcf.gz CONTROL_samples_SNPS.vcf.
gz
##bcftools_viewVersion=1.3+htslib-1.3
##bcftools_viewCommand=view -o CHD_NDD_all_samples_SNPS.vcf CHD_NDD_all_samples_SNPS.vcf.gz
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##bcftools_viewCommand=view -o CHD_NDD_all_samples_SNPS_chr_sort_PCA.vcf -S samples_for_CHD_PCA.csv CHD_NDD_all_samples_SNPS_chr_sort.vcf
##bcftools_viewCommand=view CHD_NDD_all_samples_SNPS_PCA_ID.bcf
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  02766   00618   00714   01152   01299   00773   00928   01023   01850   006
26      00734   02503   00720   01330   00748   00646   01506   01537   02261   01365   01388   01832   03062   01925   01162   00918   02237   018
33      00786   00768   01581   01584   01589   01697   01941   01953   01955   01957   01962   01963   01967   01970   01972   01974   01979
chr1    107683715       .       C       T       .       PASS    ADP=542;WT=0;HET=1;HOM=0;NC=0;AC=2;AN=4 GT:GQ:SDP:DP:RD:AD:FREQ:PVAL:RBQ:ABQ:RDF:RD
R:ADF:ADR       ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   0/1:255:551:542:269:273:50.37%:3.6098E-103:36:39:52
:217:73:200     ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   0/1:255:719:707:367:340:48.09%:8.9707E-127:36:40:92:275:76:264  ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.
chr1    107690692       .       G       A       .       PASS    ADP=285;WT=0;HET=1;HOM=0;NC=0;AC=1;AN=2 GT:GQ:SDP:DP:RD:AD:FREQ:PVAL:RBQ:ABQ:RDF:RD
R:ADF:ADR       ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      0/1:255:293:285:139:146:51.23%:9.9479E-56:40:34:128:11:135:11   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.
:.:.:.:.:.:.:.:.:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.:.
:.:.:.:.:.      ./.:.:.:.:.:.:.:.:.:.:.:.:.:.

I have also attached the input file and hope you can help me in resolving this file opening error.

Thanks.
Eddie
[CHD_NDD_all_samples_SNPS_PCA_ID.zip](https://github.com/Illumina/akt/files/734473/CHD_NDD_all_samples_SNPS_PCA_ID.zip)

**Comment by eddip** [comment]
Just wondering is a index required for the bcf file (.csi)?

Thanks.
Eddie

**Comment by eddip** [comment]
I believe my issue is from not having an index for the bcf file.

Sorry.
Eddie

**Comment by jaredo** [comment]
Yes index is required with `-R/-F`. I should add a better error message here.

**Comment by jaredo** [comment]
More informative message added in 8d1fb17
