### ISSUE TITLE
akt pca error : Failed to read the regions: pca.bcf

### ISSUE THREAD

**Issue by eddip** [Illumina/akt#15]
Hi there,

Having an issue using the akt pca when projecting another set of samples into a previously created set of principal components.

I'm trying to follow the procedure given in the akt/doc/usage.md, where an initial sample is used to create a set of precalculated PC values, and then a new set of samples are projected on to it.

So my steps:

$ /g/data/a32/Software/akt/akt pca 1000G_match_CHD_NDD_chr.bcf -R /g/data/a32/Software/akt/data/wes.hg19.vcf.gz -O b -o pca.bcf > pca.txt
Input: 1000G_match_CHD_NDD_chr.bcf
MAF lower bound: 0
Thin: 1
Number principle components: 20
Reading data...
2504 samples
166/32136 of study markers were in the sites file
Printing coefficients to pca.bcf

$ /g/data/a32/Software/akt/akt pca CHD_NDD_all_samples_SNPS_PCA_ID.bcf -W pca.bcf > projections
Input: /short/a32/exi569/GB_CHD_NDD/CHD_NDD_all_samples_SNPS_PCA_ID.bcf
Using file pca.bcf for PCA weights
Failed to read the regions: pca.bcf

Hope I'm not doing something stupid.

Thanks for your assistance in advance. 
Eddie

**Comment by jaredo** [comment]
Hi Eddie,

Apologies, the documentation was slightly out of date. The `-W` needs to be a tabix vcf file. So if you did:
```
/g/data/a32/Software/akt/akt pca 1000G_match_CHD_NDD_chr.bcf -R /g/data/a32/Software/akt/data/wes.hg19.vcf.gz -Oz -o pca.vcf.gz > pca.txt
g/data/a32/Software/akt/akt pca CHD_NDD_all_samples_SNPS_PCA_ID.bcf -W pca.vcf.gz
```
it should work. The reason for this is that (I think) htslib requires gzipped vcf for tabix jumping and this speeds things up greatly.

I am actually concerned about this line though:
```
166/32136 of study markers were in the sites file
```
it looks like very few of your variants intersect with our provided SNP set. I don't think you will get a very good PCA from this. Is this a gene panel? And is the reference genome hg19?

best,

Jared

PS. I have added a more information warning message and updated the documentation.

**Comment by eddip** [comment]
Thanks for the quick response Jared. I will give it a try when I get back in the office.

Yes, the input set is variants from a gene panel, so that would explain the low number. Reference is hg19.

I was hoping to run the pca without the -R in the initial step to utilise more of the variants in the gene panel (~2500), but when I had the issue at the projection step I decide to follow the example given, which used the -R option to check if that worked or not.

Thanks again. Hopefully it will all work now for my files.
Eddie

**Comment by rudyarthur** [comment]
You probably want to index pca.vcf.gz after generating it as the file readers in AKT always have require_index = true.

**Comment by jaredo** [comment]
Probably you want to filter your data before doing the pca, removing low-frequency variants, indels (unreliable) and non-passing sites.

Something like:

```
bcftools view -v snps -f PASS -i 'AC>=5 && AN>=(2*N_SAMPLES)' data.bcf -Ob -o filtered.bcf
```
if you still have a lot of variants (I don't know what your panel is like, then LD-prune):
```
./akt prune filtered.bcf -o pruned.sites.vcf.gz
```
then use `-R pruned.sites.vcf.gz`   in pca

**Comment by eddip** [comment]
Thanks for all the hints guys.

**Comment by eddip** [comment]
All good. Thanks again guys.

**Comment by jaredo** [comment]
great!
