### ISSUE TITLE
Error on suse11.1

### ISSUE THREAD

**Issue by colindaven** [Illumina/akt#16]
Hi. Any ideas here ? 

Thanks.

make
echo '#define VERSION "c966c25"' > version.h
echo '#define BCFTOOLS_VERSION "1.3"' >> version.h
g++ -O3  -fopenmp -mpopcnt -c tdt.cpp -Ihtslib-1.3  -I./
g++ -O3  -fopenmp -mpopcnt -c admix.cpp -Ihtslib-1.3  -I./
In file included from htslib-1.3/htslib/synced_bcf_reader.h:56,
                 from akt.hpp:44,
                 from admix.cpp:3:
htslib-1.3/htslib/vcf.h: In function ‘void bcf_format_gt(bcf_fmt_t*, int, kstring_t*)’:
htslib-1.3/htslib/vcf.h:817: error: ‘INT8_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h:818: error: ‘INT16_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h:819: error: ‘INT32_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h: In function ‘int bcf_enc_inttype(long int)’:
htslib-1.3/htslib/vcf.h:848: error: ‘INT8_MAX’ was not declared in this scope
htslib-1.3/htslib/vcf.h:848: error: ‘INT8_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h:849: error: ‘INT16_MAX’ was not declared in this scope
htslib-1.3/htslib/vcf.h:849: error: ‘INT16_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h: In function ‘void bcf_enc_int1(kstring_t*, int32_t)’:
htslib-1.3/htslib/vcf.h:855: error: ‘INT32_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h:857: error: ‘INT8_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h:860: error: ‘INT8_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h:861: error: ‘INT8_MAX’ was not declared in this scope
htslib-1.3/htslib/vcf.h:861: error: ‘INT8_MIN’ was not declared in this scope
htslib-1.3/htslib/vcf.h:864: error: ‘INT16_MAX’ was not declared in this scope
htslib-1.3/htslib/vcf.h:864: error: ‘INT16_MIN’ was not declared in this scope
make: *** [admix.o] Error 1

**Comment by colindaven** [comment]
Seems to be a GLIBC incompatibility as expected, compiled fine on Ubuntu 16.04 and reported following errors on Suse11.1.

./akt: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by ./akt)
./akt: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./akt)
./akt: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./akt)
./akt: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./akt)
./akt: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./akt)

**Comment by jaredo** [comment]
This is probably an easy fix, will find a suse vm and look into it.
