### ISSUE TITLE
Bad genotypes at ...?

### ISSUE THREAD

**Issue by IanCodes** [Illumina/akt#18]
Hi,

I have run 'akt pca' with the following command line:
`~/sources/akt/akt pca --force chr1_all_sample.bcf > pca.txt`

But I get the following error:
```
Input: chr1_all_sample.bcf
MAF lower bound: 0
Thin: 1 
Number principle components: 20
Reading data...
12 samples
Bad genotypes at chr1:10004
```
chr1_all_sample.bcf has been indexed.  The genotypes are the result of a 'bcftool call' analysis, restricted here to chr1.

Can you suggest a cause for the error?

Thank you,
Ian

**Comment by jaredo** [comment]
This means there was an htslib error code for that line.  Our akt error reporting could be improved in this instance!

What does `bcftools view -r chr1:10004 -H chr1_all_sample.bcf` look like?

Note that more generally, running a PCA on a large unfiltered/unpruned call set will likely cause a number of issues. There will be a lot of poor quality genotypes in there and the matrix might be very large.

**Comment by IanCodes** [comment]
chr1	10004	.	C	<*>	0	.	DP=2;I16=2,0,0,0,64,2048,0,0,0,0,0,0,0,0,0,0;QS=2,0;MQ0F=1	PL	0,0,0	0,0,0	0,0,0	0,0,0	0,3,4	0,0,0	0,0,0	0,0,0	0,3,4	0,0,0	0,0,0	0,0,0

OK, that does look awful.  Thanks for the tip.  Can you recommend a way of filtering the BCF file to retain only those positions that have coverage in every sample?

**Comment by jaredo** [comment]
(edited) I think this is output from `bcftools mpileup` ie. not actual variant calls. To produce variant calls with bcftools, use something roughly like:

```
bcftools mpileup -r chr1 input.bam -f $ref | bcftools call -mv -Ob -o variants.bcf
```

then you need to filter to high quality sites and prune. If this is human data, the easiest thing to do is leverage one of our pre-calculated SNP lists (under the data directory):

```
./akt pca -R data/wgs.grch37.vcf.gz input.bcf
```
