### ISSUE TITLE
ibd options

### ISSUE THREAD

**Issue by AntilMB** [Illumina/akt#23]
Hello
This [document](https://github.com/Illumina/akt/blob/master/docs/ibd.md) describes calling the ibd option.
The following error occurs, when I call ibd option:
`alexander@statistics-dev:/mnt/fs/akt$ ./akt ibd input.bcf -R panel.bcf -r 2 > sharing`
`ERROR: ibd is deprecated`
`Exiting...`
So, how can I run searching for IBD segments?

**Comment by jaredo** [comment]
Apologies, we deprecated the `akt ibd` functionality some time ago but I forgot to remove it from the documentation. If you want to find IBD segments, I would recommend [Beagle](https://faculty.washington.edu/browning/beagle/beagle.html) or [ibdseq](http://faculty.washington.edu/browning/ibdseq.html).

I have fixed the documentation - sorry for the confusion.

Jared
