### ISSUE TITLE
recent github release tarball?

### ISSUE THREAD

**Issue by daler** [Illumina/akt#25]
Thanks for `akt`. I'm currently working on building an `akt` package for Bioconda based on the latest available release tarball from github (https://github.com/bioconda/bioconda-recipes/pull/8661), which is v0.2.0.

I'd like to also eventually build an updated version, since I see there have been quite a few changes since the 2016 release of v0.2.0.

Would you be able to create a github release of `akt` for a more recent version so we can build a bioconda recipe for it? Thanks.

**Comment by stephenturner** [comment]
👍 to this, would be great to keep current releases in bioconda. thanks @jaredo

**Comment by jaredo** [comment]
Will do shortly.

**Comment by jaredo** [comment]
Done. Thanks for your interest!

**Comment by daler** [comment]
Thanks! v0.2.0 and v0.3.2 are now both available bioconda (https://anaconda.org/bioconda/akt/files).
