### ISSUE TITLE
new kinship matrices

### ISSUE THREAD

**Issue by jaredo** [Illumina/akt#6]
We should add options to `akt kin` to calculate the:
- [genetic relationship matrix](http://cnsgenomics.com/software/gcta/manipulation_grm.html)
- a robust kinship estimator such as [king](http://bioinformatics.oxfordjournals.org/content/26/22/2867.short) or [REAP](http://faculty.washington.edu/tathornt/software/REAP/download.html)

**Comment by rudyarthur** [comment]
The kinship coefficient calculated by KING and the one calculated by AKT is the same if the AFs are provided, which is the use case we want people to use. I did implement equation 7 in the KING paper at some point and for big enough sample sizes there isn't much difference, and I don't recall any particularly good reasons to prefer this one over the current one.

The thing in 
http://www.well.ox.ac.uk/dtc/Genetic%20Analysis.pdf
Is not too difficult to calculate (If the usual correlation matrix is MM^T then this is M^TM)
- should this be a separate command or a part of kin?

**Comment by jaredo** [comment]
I was planning to add an option to kin to choose which matrix to output:

```
-K, --kinship-matrix 0:plink unnormalised 1: plink normalised 2: KING-robust 3:genetic relationship matrix
```

so the default `akt kin` behaviour would remain the same.

I was planning to implement eq11 in the KING paper which works well in the presence of population structure:

![e8151b04-ef66-11e5-8638-0d95c11bec95](https://cloud.githubusercontent.com/assets/349198/15958157/cb035fe8-2eeb-11e6-9979-eba07d0fa9e3.png)

**Comment by rudyarthur** [comment]
It's kind of ugly and confusing having several, basically equivalent, estimators of the same thing as well as we should be encouraging people to use PCA to discover population structure instead of kinship. But if you are going to implement it I think the only things you need are

```
for(size_t i=0; i<bits[j1].size(); ++i){
      IBD[0][j1][j2] += (bits[j1][i][0] & bits[j2][i][2]).count() + (bits[j1][i][2] & bits[j2][i][0]).count();  ///opposite homozygotes = NAA,aa
      ...
      Nhet_1 += bits[j1][i][1].count(); //NAa^i
      Nhet_2 += bits[j2][i][1].count(); //NAa^j
      Nhet_12 += (bits[j1][i][1] & bits[j2][i][1]).count(); //NAa,Aa
    }
```

**Comment by jaredo** [comment]
Thanks. I think it is okay to have options as long as default behaviour does something clear and useful.

I agree the KING-robust estimator is somewhat superfluous (like in the above I can tell they are parent-child relationships even if kinship=0.3) but it is straightforward to add and will keep reviewers happy. The GRM is a better matrix for [certain applications](http://keppel.qimr.edu.au/contents/p/staff/hayes_genet_res.pdf), might be useful for future functionality.

**Comment by rudyarthur** [comment]
GRM elements seem to just be correlation between individuals i and j, since it is actually a different quantity than kinship (but closely related) I guess is fine. FYI - if you want to calculate something like

```
 sum_{SNPS} (g_ik - mu_k)(g_jk - mu_k)
```

It is slow to calculate it the naive way.
Split it up

```
 sum_{SNPS} g_ik g_jk - sum_{SNPS} mu_k g_ik  - sum_{SNPS} mu_k g_jk +  - sum_{SNPS} mu_k^2
```

The last 3 terms can be calculated once and saved while reading the allele frequencies, the first term can be calculated from the bitsets

```
sum_{SNPS} g_ik g_jk = (bits[j1][i][1] & bits[j2][i][1]).count() + 2*(bits[j1][i][1] & bits[j2][i][2]).count() + 2*(bits[j1][i][2] & bits[j2][i][1]).count() + 4*(bits[j1][i][2] & bits[j2][i][2]).count();
```

just because the bitset stuff can be a bit cryptic but it is a lot faster.

**Comment by jaredo** [comment]
great thanks!

**Comment by rudyarthur** [comment]
Also mu_k here is 2*AF!

**Comment by jaredo** [comment]
Got this mostly working. What should the default be? Plink normalised or plink unnormalised?

I had assumed it was unnormalised for the relatives clustering, but noticed this was not the case.

**Comment by rudyarthur** [comment]
I think PLINK normalised. Perhaps you could even get rid of the unnormalized option since no one will ever use it.

**Comment by jaredo** [comment]
ok. will do.

**Comment by jaredo** [comment]
I think you were right that GRM should be its own subcommand, the routine does not naturally lead to estimates of IBD0/IBD1/IBD2 so the output format will be different. Hence I have added `akt grm`.  The king estimator is an option on `akt kin` since we can easily produce the IBD estimators from it.

The differences are interesting. Here is 2*kinship for all the pairs in the CG data. GRM seems the most sensitive to population structure (which is a probably good feature for its intended use). I like that the king estimator is usually very close to 0.5 for the parent-child pairs whilst the plink one is slightly inflated.

![kinship](https://cloud.githubusercontent.com/assets/349198/16010457/28cb8512-3179-11e6-82c0-7b011c168e02.png)

**Comment by rudyarthur** [comment]
I am fine with that - but I am pretty sure GRM can be computed from the same counts and frequencies as IBD, unless you are using something fancier than the simple correlation formula.

How long does it take? If it is significantly slower than kin code I will have a look at it. Though that shouldn't stop you from considering this done if you are happy with it.

**Comment by jaredo** [comment]
hmmm...I did try that and the values looked fine, but I was a bit worried about potential loss of precision.  I think the "one pass" approach has the same issue as variance/covariance algorithms see: https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance

Turns out there is another [fast way to do it](https://www.cog-genomics.org/plink2/dev). For any given allele frequency there are only nine possible values for (g_i - 2p)_(g_j -2_p)/(2_p_q).  So you can just build a lookup table for each SNP and sum from the lookup table. Compute time is nearly exactly the same as `akt kin`.

Given the above results, GRM actually looks the _least_ useful to me for QC purposes. It is nice to have there for completeness, but I am not too worried about improving the routine.

**Comment by rudyarthur** [comment]
You could always convert to double, but if the 4th decimal place in the variance matters then sequencing is much more accurate than I thought :) 

Seriously though, I think adding an extra subcommand makes AKT more unwieldy to maintain and document, as well as difficult for people to remember how to use - especially when something as similar as GRM and kinship are computed with different subcommands. I think a potential loss of precision (which I have never found to be a problem in practice) is worth potential inflation of code. But I leave it to you in the end, especially when it comes to satisfying referees before the deadline for re-submission.

**Comment by jaredo** [comment]
Okay, lets put grm in has `akt kin --method 2`.
